themesDir = "themes"
baseURL = 'https://centros-geriatricos-mahatma.netlify.app/'
languageCode = 'es-AR'
title = 'Centros Geriátricos Mahatma'
theme = "hugo-celadon"
enableRobotsTXT = true


[params]
  description = 'Centros Geriátricos Mahatma'
  google_place_id_1 = 'ChIJe6JOTC2lvpUR3xQPnWXvuUs'
  google_place_id_2 = 'ChIJmVlx1JulvpURg33MNt_ACFQ'
  google_place_id_3 = 'ChIJ1zTamtulvpUREwzBmZvI0Wo'
  email = 'geriatricosmahatma@gmail.com'
  location = 'Chivilcoy, Buenos Aires, Argentina'
  avatar = "static/portrait.png"
  automaticMenu = false
  disableHomeLink = true

[params.homepage]
  sections = ["hero", "nuestros-hogares", "staff", "empleadx", "contacto"]

  [params.homepage.hero]
    enable = true
    layout = "hero"
    title = "Nosotros"

  [params.homepage."nuestros-hogares"]
    enable = true
    layout = "cards"
    title = "Nuestros Hogares"

  [params.homepage.staff]
    enable = true
    layout = "staff"
    title = "Staff"

  [params.homepage.empleadx]
    enable = true
    layout = "empleadx"
    title = ""
    showInMenu = false
  
  [params.homepage.contacto]
    enable = true
    layout = "contacto"
    title = "Contacto"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        enableInShortcodes = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [
            ["\\[", "\\]"],
            ["$$", "$$"]
          ]
          inline = [
            ["\\(", "\\)"],
            ["$", "$"]
          ]
  [markup.highlight]
    style = "friendly"
    noClasses = false
    lineNos = true
    guessSyntax = true

# ---------------------------------------------------------
# CASCADING DEFAULTS
# This applies settings to ALL files in the 'content' folder
# ---------------------------------------------------------

[[cascade]]
  layout = "single"      # 1. The Rule: Use single.html
  [cascade._target]
    path = "/**"         # 2. The Scope: Inside any folder (** = "Recursive")
    kind = "page"        # 3. The Filter: But ONLY for regular text files

# ---------------------------------------------------------
# CONFIGURACIÓN DEL MENÚ DE NAVEGACIÓN (HEADER)
# Mantiene tus secciones intactas pero te da los links correctos
# ---------------------------------------------------------


[[menus.main]]
  name = "Nosotros"
  url = "/#hero"
  weight = 1

[[menus.main]]
  name = "Nuestros Hogares"
  url = "/#nuestros-hogares"
  weight = 2

[[menus.main]]
  name = "Staff"
  url = "/#staff"
  weight = 3

[[menus.main]]
  name = "Contacto"
  url = "/#contacto"
  weight = 4